export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
export const BLOCK_PAGE = "BLOCK_PAGE";
export const OPEN_WEB_VIEW = "OPEN_WEB_VIEW";

export const HIDE_CUSTOM_LOADER = "HIDE_CUSTOM_LOADER";
export const SHOW_CUSTOM_LOADER = "SHOW_CUSTOM_LOADER";

export const ENABLE_RTL = "ENABLE_RTL";
export const DISABLE_RTL = "DISABLE_RTL";
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
export const SHOW_CONFIRM_DIALOGUE = "SHOW_CONFIRM_DIALOGUE";
export const HIDE_CONFIRM_DIALOGUE = "HIDE_CONFIRM_DIALOGUE";
export const SHOW_HELP_DIALOGUE = "SHOW_HELP_DIALOGUE";
export const HIDE_HELP_DIALOGUE = "HIDE_HELP_DIALOGUE";

export const ADD_RECORD = "ADD_RECORD";
export const REMOVE_RECORD = "REMOVE_RECORD";
export const SELECT_ALL_RECORDS = "SELECT_ALL_RECORDS";
export const SET_SELECT_MODE = "SET_SELECT_MODE";
export const CLEAR_ALL = "CLEAR_ALL";

export const RESTORE_TOKEN = "RESTORE_TOKEN";
export const SIGN_IN = "SIGN_IN";
export const CLEAR_SIGN_UP = "CLEAR_SIGN_UP";

export const SIGN_OUT = "SIGN_OUT";
export const UPDATEUSERDATA = "UPDATEUSERDATA";
export const GET_PROVIDERS = "GET_PROVIDERS";
export const GET_PROVIDERS_STARTED = "GET_PROVIDERS_STARTED";
export const GET_MY_PROVIDERS = "GET_MY_PROVIDERS";
export const CLEAR_PROVIDERS = "CLEAR_PROVIDERS";
export const UPDATE_PROVIDERS = "UPDATE_PROVIDERS";
export const SET_REMINDER_NAVIGATED = "SET_REMINDER_NAVIGATED";

export const SET_LINKS = "SET_LINKS";
export const REMOVE_LINK = "REMOVE_LINK";
export const UPDATE_EXPIRY_DATE = "UPDATE_EXPIRY_DATE";
export const SET_RECORDS = "SET_RECORDS";
export const ENABLE_EDIT_SHARE_BUTTON = "ENABLE_EDIT_SHARE_BUTTON";
export const DISABLE_EDIT_SHARE_BUTTON = "DISABLE_EDIT_SHARE_BUTTON";



